[package]
name = "rustmap-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde     = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
