[package]
name = "rustmap-output"
version.workspace = true
edition.workspace = true

[dependencies]
rustmap-types = { workspace = true }
thiserror     = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
serde_yaml    = { workspace = true }
